const constants = {
  // without an api call
  SAVE_USER_COORDS: 'COORDS::SAVE_USER_COORDS',
  SAVE_CURRENT_DAY: 'COORDS::SAVE_CURRENT_DAY',
  SAVE_SELECTED_DEGREE_TYPE: 'COORDS::SAVE_SELECTED_DEGREE_TYPE',

  // with an api call
  // generally we add PENDING/REJECTED but here we dont need it
  SAVE_SELECTED_POSITION_WEATHER: 'COORDS::SAVE_SELECTED_POSITION_WEATHER',
  SAVE_SELECTED_POSITION_WEATHER_FULFILLED: 'COORDS::SAVE_SELECTED_POSITION_WEATHER_FULFILLED',

  SAVE_SELECTED_PLACE: 'COORDS::SAVE_SELECTED_PLACE',
  SAVE_SELECTED_PLACE_FULFILLED: 'COORDS::SAVE_SELECTED_PLACE_FULFILLED',

};

export default constants;