const constants = {
  // without an api call
  SAVE_USER_COORDS: 'COORDS::SAVE_USER_COORDS',
  SAVE_CURRENT_DAY: 'COORDS::SAVE_CURRENT_DAY',
  SAVE_SELECTED_DEGREE_TYPE: 'COORDS::SAVE_SELECTED_DEGREE_TYPE',

  // with an api call
  SAVE_SELECTED_POSITION_WEATHER: 'COORDS::SAVE_SELECTED_POSITION_WEATHER',
  SAVE_SELECTED_POSITION_WEATHER_FULFILLED: 'COORDS::SAVE_SELECTED_POSITION_WEATHER_FULFILLED'

};

export default constants;